version: "3"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/workspace:cached
        command: /bin/sh -c "while sleep 1000; do :; done"
        ports:
            - "3000:3000"
        depends_on:
            - postgres_db

    postgres_db:
        image: postgres:latest
        restart: always
        env_file:
            - database.env
        volumes:
            - myapp-db:/var/lib/postgresql/data
        ports:
            - "5432:5432"

volumes:
    myapp-db:
